-- 
-- drop table AQ$_INTERNET_AGENTS;
-- drop table AQ$_INTERNET_AGENT_PRIVS;
-- drop table AQ$_QUEUES;
-- drop table AQ$_QUEUE_TABLES;
-- drop table AQ$_SCHEDULES;
-- drop table DEF$_AQCALL;
-- drop table DEF$_AQCALL;
-- drop table DEF$_AQERROR;
-- drop table DEF$_AQERROR;
-- drop table DEF$_CALLDEST;
-- drop table DEF$_DEFAULTDEST;
-- drop table DEF$_DESTINATION;
-- drop table DEF$_ERROR;
-- drop table DEF$_LOB;
-- drop table DEF$_ORIGIN;
-- drop table DEF$_PROPAGATOR;
-- drop table DEF$_PUSHED_TRANSACTIONS;
-- drop table HELP;
-- drop table LOGMNRC_DBNAME_UID_MAP;
-- drop table LOGMNRC_GSBA;
-- drop table LOGMNRC_GSII;
-- drop table LOGMNRC_GTCS;
-- drop table LOGMNRC_GTLO;
-- drop table LOGMNRP_CTAS_PART_MAP;
-- drop table LOGMNRT_MDDL$;
-- drop table LOGMNR_AGE_SPILL$;
-- drop table LOGMNR_ATTRCOL$;
-- drop table LOGMNR_ATTRIBUTE$;
-- drop table LOGMNR_CCOL$;
-- drop table LOGMNR_CDEF$;
-- drop table LOGMNR_COL$;
-- drop table LOGMNR_COLTYPE$;
-- drop table LOGMNR_DICTIONARY$;
-- drop table LOGMNR_DICTSTATE$;
-- drop table LOGMNR_ENC$;
-- drop table LOGMNR_ERROR$;
-- drop table LOGMNR_FILTER$;
-- drop table LOGMNR_GLOBAL$;
-- drop table LOGMNR_GT_TAB_INCLUDE$;
-- drop table LOGMNR_GT_USER_INCLUDE$;
-- drop table LOGMNR_GT_XID_INCLUDE$;
-- drop table LOGMNR_ICOL$;
-- drop table LOGMNR_IND$;
-- drop table LOGMNR_INDCOMPART$;
-- drop table LOGMNR_INDPART$;
-- drop table LOGMNR_INDSUBPART$;
-- drop table LOGMNR_INTEGRATED_SPILL$;
-- drop table LOGMNR_KOPM$;
-- drop table LOGMNR_LOB$;
-- drop table LOGMNR_LOBFRAG$;
-- drop table LOGMNR_LOG$;
-- drop table LOGMNR_LOGMNR_BUILDLOG;
-- drop table LOGMNR_NTAB$;
-- drop table LOGMNR_OBJ$;
-- drop table LOGMNR_OPQTYPE$;
-- drop table LOGMNR_PARAMETER$;
-- drop table LOGMNR_PARTOBJ$;
-- drop table LOGMNR_PROCESSED_LOG$;
-- drop table LOGMNR_PROPS$;
-- drop table LOGMNR_REFCON$;
-- drop table LOGMNR_RESTART_CKPT$;
-- drop table LOGMNR_RESTART_CKPT_TXINFO$;
-- drop table LOGMNR_SEED$;
-- drop table LOGMNR_SESSION$;
-- drop table LOGMNR_SESSION_ACTIONS$;
-- drop table LOGMNR_SESSION_EVOLVE$;
-- drop table LOGMNR_SPILL$;
-- drop table LOGMNR_SUBCOLTYPE$;
-- drop table LOGMNR_TAB$;
-- drop table LOGMNR_TABCOMPART$;
-- drop table LOGMNR_TABPART$;
-- drop table LOGMNR_TABSUBPART$;
-- drop table LOGMNR_TS$;
-- drop table LOGMNR_TYPE$;
-- drop table LOGMNR_UID$;
-- drop table LOGMNR_USER$;
-- drop table LOGSTDBY$APPLY_MILESTONE;
-- drop table LOGSTDBY$APPLY_PROGRESS;
-- drop table LOGSTDBY$EDS_TABLES;
-- drop table LOGSTDBY$EVENTS;
-- drop table LOGSTDBY$FLASHBACK_SCN;
-- drop table LOGSTDBY$HISTORY;
-- drop table LOGSTDBY$PARAMETERS;
-- drop table LOGSTDBY$PLSQL;
-- drop table LOGSTDBY$SCN;
-- drop table LOGSTDBY$SKIP;
-- drop table LOGSTDBY$SKIP_SUPPORT;
-- drop table LOGSTDBY$SKIP_TRANSACTION;
-- drop table MVIEW$_ADV_AJG;
-- drop table MVIEW$_ADV_BASETABLE;
-- drop table MVIEW$_ADV_CLIQUE;
-- drop table MVIEW$_ADV_ELIGIBLE;
-- drop table MVIEW$_ADV_EXCEPTIONS;
-- drop table MVIEW$_ADV_FILTER;
-- drop table MVIEW$_ADV_FILTERINSTANCE;
-- drop table MVIEW$_ADV_FJG;
-- drop table MVIEW$_ADV_GC;
-- drop table MVIEW$_ADV_INFO;
-- drop table MVIEW$_ADV_JOURNAL;
-- drop table MVIEW$_ADV_LEVEL;
-- drop table MVIEW$_ADV_LOG;
-- drop table MVIEW$_ADV_LOG;
-- drop table MVIEW$_ADV_OUTPUT;
-- drop table MVIEW$_ADV_PARAMETERS;
-- drop table MVIEW$_ADV_PLAN;
-- drop table MVIEW$_ADV_PRETTY;
-- drop table MVIEW$_ADV_ROLLUP;
-- drop table MVIEW$_ADV_SQLDEPEND;
-- drop table MVIEW$_ADV_TEMP;
-- drop table MVIEW$_ADV_WORKLOAD;
-- drop table OL$;
-- drop table OL$HINTS;
-- drop table OL$NODES;
drop table REPCAT$_AUDIT_COLUMN;
drop table REPCAT$_DDL;
drop table REPCAT$_EXCEPTIONS;
drop table REPCAT$_FLAVOR_OBJECTS;
drop table REPCAT$_GENERATED;
drop table REPCAT$_GROUPED_COLUMN;
drop table REPCAT$_INSTANTIATION_DDL;
drop table REPCAT$_KEY_COLUMNS;
drop table REPCAT$_OBJECT_PARMS;
drop table REPCAT$_PARAMETER_COLUMN;
drop table REPCAT$_PRIORITY;
drop table REPCAT$_PRIORITY_GROUP;
drop table REPCAT$_REPCATLOG;
drop table REPCAT$_REPCOLUMN;
drop table REPCAT$_REPGROUP_PRIVS;
drop table REPCAT$_REPPROP;
drop table REPCAT$_REPSCHEMA;
drop table REPCAT$_RESOLUTION;
drop table REPCAT$_RESOLUTION_METHOD;
drop table REPCAT$_RESOLUTION_STATISTICS;
drop table REPCAT$_RESOL_STATS_CONTROL;
drop table REPCAT$_RUNTIME_PARMS;
drop table REPCAT$_SITES_NEW;
drop table REPCAT$_SITE_OBJECTS;
drop table REPCAT$_SNAPGROUP;
drop table REPCAT$_TEMPLATE_OBJECTS;
drop table REPCAT$_TEMPLATE_REFGROUPS;
drop table REPCAT$_TEMPLATE_SITES;
drop table REPCAT$_TEMPLATE_TARGETS;
drop table REPCAT$_USER_AUTHORIZATIONS;
drop table REPCAT$_USER_PARM_VALUES;
drop table REPCAT$_TEMPLATE_PARMS;
drop table REPCAT$_REPOBJECT;
drop table REPCAT$_REFRESH_TEMPLATES;
drop table REPCAT$_OBJECT_TYPES;
drop table REPCAT$_FLAVORS;
drop table REPCAT$_EXTENSION;
drop table REPCAT$_CONFLICT;
drop table REPCAT$_COLUMN_GROUP;
drop table REPCAT$_AUDIT_ATTRIBUTE;
drop table REPCAT$_TEMPLATE_STATUS;
drop table REPCAT$_TEMPLATE_TYPES;
drop table REPCAT$_REPCAT;
drop type REPCAT$_OBJECT_NULL_VECTOR;

-- drop table SQLPLUS_PRODUCT_PROFILE;
